# build flags
CXX_FLAGS = -std=c++11 -Wall -Werror

# make all problems
all: queue_at_the_school

# queue at the school
queue_at_the_school:
	$(CXX) $(CXX_FLAGS) queue_at_the_school.cc -o queue_at_the_school

clean:
	@- $(RM) queue_at_the_school