# build flags
CXX_FLAGS = -std=c++11 -Wall -Werror

# make all problems
all: seven_number

# seven number
seven_number:
	$(CXX) $(CXX_FLAGS) seven_number.cc -o seven_number

clean:
	@- $(RM) seven_number